### ISSUE TITLE
Some tests lack a segment override prefix?

### ISSUE THREAD

**Issue by lesserfish** [SingleStepTests/8088#2]
Hello!

I'm sorry if this is a really stupid question, I'm kind of new to the x86. I'm looking at some of the 00 tests and I'm not certain how to establish whether or not the add instruction is preceded by a segment override prefix. It seems some tests have them, and some do not.

For example, test 19:

```
{
    "name": "add byte [ss:bx+di+436Bh], dh",
    "bytes": [54, 0, 177, 107, 67],
    "initial": {
        "regs": {
            "ax": 47967,
            "bx": 17148,
            "cx": 21552,
            "dx": 9062,
            "cs": 24676,
            "ss": 56756,
            "ds": 15976,
            "es": 43448,
            "sp": 13242,
            "bp": 54400,
            "si": 56083,
            "di": 33416,
            "ip": 24304,
            "flags": 63511
        },
        "ram": [
            [419120, 54],
            [419121, 0],
            [419122, 177],
            [419123, 107],
            [419124, 67],
            [910383, 108]
        ],
        "queue": []
    },
    "final": {
        "regs": {
            "ip": 24309,
            "flags": 63618
        },
        "ram": [
            [910383, 143]
        ],
        "queue": [144, 144]
    },
    ....
    "idx": 19
},
```

The instruction `add byte [ss:bx+di+436Bh], dh` does indeed compile to `[36h, 00h, b1h, 6bh, 43h] = [54, 0, 177, 107, 67]`. Here `36h` is the Stack Segment override prefix, and this is followed by the correct add instruction. No problem here.

However, test 0 looks like this:

```
{
    "name": "add byte [ss:bp+di-64h], cl",
    "bytes": [0, 75, 156],
    "initial": {
        "regs": {
            "ax": 21153,
            "bx": 59172,
            "cx": 33224,
            "dx": 61687,
            "cs": 12781,
            "ss": 7427,
            "ds": 600,
            "es": 52419,
            "sp": 49014,
            "bp": 9736,
            "si": 52001,
            "di": 10025,
            "ip": 694,
            "flags": 62546
        },
        "ram": [
            [205190, 0],
            [205191, 75],
            [205192, 156],
            [205193, 144],
            [138493, 20]
        ],
        "queue": [0, 75, 156, 144]
    },
    "final": {
        "regs": {
            "ip": 697,
            "flags": 62594
        },
        "ram": [
            [138493, 220]
        ],
        "queue": [144, 144, 144]
    },
    ....
    "idx": 0
}
```

The code `add byte [ss:bp+di-64h], cl`, according to NASM, compiles to `[36h, 00h, 4bh, 9ch]`. However, the RAM data in the test only includes `[00h, 4bh, 9ch]`.

Unless I am mistaken, `[00h, 4bh, 9ch]` is the opcode for `add byte [bp+di-64h], cl`, not `add byte [ss:bp+di-64h], cl`.

Perhaps I am lacking knowledge regarding some specific functionality or behavior of the 8088. Without parsing the name, can you please help me understand how to establish whether or not a test is preceded by a segment override prefix?

Thank you very much for your help, and I hope this question is not too stupid.

**Comment by dbalsom** [comment]
Not a stupid question. You are correct, only some of the instructions have prefixes. It is randomized. The easiest way to check if an instruction starts with an override prefix is to just check the first byte against the list of prefix opcodes. 

I'm being lazy here and just pasting from source:
```
  0x26 => OPCODE_PREFIX_ES_OVERRIDE,
  0x2E => OPCODE_PREFIX_CS_OVERRIDE,
  0x36 => OPCODE_PREFIX_SS_OVERRIDE,
  0x3E => OPCODE_PREFIX_DS_OVERRIDE,
  0xF0 => OPCODE_PREFIX_LOCK,
  0xF1 => OPCODE_PREFIX_LOCK,
  0xF2 => OPCODE_PREFIX_REP1,
  0xF3 => OPCODE_PREFIX_REP2,
```

In regards to `add byte [bp+di-64h], cl` vs `add byte [ss:bp+di-64h], cl`, my disassembler always emits the effective segment. This differs from other disassemblers which will only show it when an override prefix is present.  In fact `add byte [ss:bp+di-64h], cl` has no prefix. Keep in mind when BP is used in an EA calculation, SS is the base register, not DS.

NASM seems to emit a redundant prefix if you include the segment specifier in this case.

**Comment by lesserfish** [comment]
> Keep in mind when BP is used in an EA calculation, SS is the base register, not DS.

Ah, I was missing this piece of information! I was under the impression that all 'add' instructions used the DS as the default segment. 

I see, so the information provided on ram should be enough to establish which segment to use to calculate the physical address.  I'll try re-reading the manual.

Thanks for the reply!

**Comment by dbalsom** [comment]
Good luck!
