### ISSUE TITLE
disassemblies in C0.json.gz seem wrong?

### ISSUE THREAD

**Issue by eboregelna** [SingleStepTests/8088#3]
First many many thanks!

One example of what seems to be an issue:
See hash 9b7620d554f04ca04dca894f2439858964efe3ae in C0.json.gz.
```

    "name": "retn E9C0h",
    "bytes": [192, 192, 233],

```
But this seems to disassemble as:
` rol al, 0xe9`
(per https://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=C0C0E9&arch=x86-16&endianness=little&baddr=0x00000000&dis_with_ins=True#disassembly, which seems consistent with https://en.wikipedia.org/wiki/X86_instruction_listings)

As far as I can see retn would be 0xc2 or 0xc3...

Am I missing something?

**Comment by eboregelna** [comment]
ah, 8086 didn't have C0. got it... sorry for the noise.

**Comment by dbalsom** [comment]
The C0 opcode on the 8088 is an alias for C2.

**Comment by dbalsom** [comment]
> ah, 8086 didn't have C0. got it... sorry for the noise.

No problem, thanks for using the tests!
